### ISSUE TITLE
removing role in discord doesnt update in pmsf by bot

### ISSUE THREAD

**Issue by Pogodenhelder** [pmsf/PHP-Authbot#1]
When i add a role to a new user its getting updated by php-authbot in the pmsf user table, so that works.
when i later on remove the role in discord from the user and run php bot again the access level doesnt get removed but stays the same its not set to 0

In the old pmsf auth bot this was done automaticly, But no role in the config must mean access level 0 and that is not being done right now.

**Comment by jepke** [comment]
@Pogodenhelder try develop branch

When a user exists in the database but does not longer has any of the configured roles in config.php it will now be updated to NULL in the manual_pmsf database.

**Comment by Pogodenhelder** [comment]
tested and develop indeed turnes people without role to NULL.

**Comment by jepke** [comment]
fixed in #2
